source "http://rubygems.org"

gem "rails", "3.0.10"
gem 'mysql'

gem 'authlogic'
gem "bcrypt-ruby", :require => "bcrypt"
gem "jammit"

gem 'muck-engine', :path => "~/projects/muck-engine"
gem 'muck-users', :path => "~/projects/muck-users"
gem 'muck-profiles', :path => "~/projects/muck-profiles"
gem 'muck-activities', :path => "~/projects/muck-activities"
gem 'muck-auth', :path => "~/projects/muck-auth"
gem 'muck-invites', :path => '../'
gem "muck-contents", :path => "~/projects/muck-contents"
gem "muck-comments", :path => "~/projects/muck-comments"

group :test, :development do
  gem "rspec-rails", ">=2.1.0"
  gem "cucumber-rails"
  gem "ruby-debug", :platform => [:ruby_18]
  gem "ruby-debug19", :platform => [:ruby_19]
end

group :test do
  gem "autotest"
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec", ">=2.1.0"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
  gem "fakeweb"
end