source :gemcutter

gem "rails", "2.3.5"
gem 'mysql'
gem "authlogic", '2.1.3'
gem 'oauth', '~> 0.3.6'
gem 'oauth-plugin', '~> 0.3.14'
gem 'twitter', '~> 0.9.5'
gem 'linkedin', '~> 0.1.2'
gem 'fireeagle', '~> 0.8.0.1'
gem 'agree2', '~> 0.2.0'
gem 'portablecontacts', '~> 0.1.0'
gem 'hpricot', '0.8.2'
gem "contacts", '1.2.3'
gem 'muck-engine', '0.4.27', :require => 'muck_engine'
gem 'muck-users', '0.3.13', :require => 'muck_users'
gem 'muck-profiles', '0.2.1', :require => 'muck_profiles'
gem 'muck-oauth', '0.2.2', :require => 'muck_oauth'
gem 'muck-activities', '0.1.27',:require => 'muck_activities'
gem 'muck-invites', :require => 'muck_invites', :path => File.join(File.dirname(__FILE__), *%w(.. .. ..))

group :development do
  gem 'ruby-debug'

  # gem 'muck-engine', :require => 'muck_engine', :path => "~/projects/muck-engine"
  # gem 'muck-users', :require => 'muck_users', :path => "~/projects/muck-users"
  # gem 'muck-activities', :require => 'muck_activities', :path => "~/projects/muck-activities"
  # gem 'muck-profiles', :require => 'muck_profiles', :path => "~/projects/muck-profiles"
  # gem 'muck-oauth', :require => 'muck_oauth', :path => "~/projects/muck-oauth"  
end

group :test do
  # bundler requires these gems while running tests
  gem 'ruby-debug'
  gem 'mocha', '>= 0.9.8'
  gem 'redgreen'
  gem 'factory_girl'
  gem 'shoulda'
  gem 'treetop', '>=1.2.4'
  gem 'term-ansicolor', '>=1.0.3', :require => 'term/ansicolor'
  gem 'cucumber', '>=0.1.13', :require => 'cucumber'
  gem 'polyglot', '>=0.2.4'
  gem "rcov", '>=0.8.1.2.0'
  gem "webrat", '>=0.4.4'
  gem 'redgreen'
  # gem 'rspec', '>=1.1.12', :require_as => 'spec'
  # gem 'rspec-rails', '>=1.1.12', :require_as => 'spec/rails'
  # only required if you want to use selenium for testing
  #gem 'selenium-client', :require_as => 'selenium/client'
  #gem 'database_cleaner'
end
